import data_structures

queue = data_structures.Static_Queue()

queue.dequeue()
queue.enqueue(1)
print(queue.list, queue.endPointer)
queue.enqueue(2)
print(queue.list, queue.endPointer)
queue.enqueue(3)
print(queue.list, queue.endPointer)
queue.dequeue()
print(queue.list, queue.endPointer)
queue.enqueue(4)
print(queue.list, queue.endPointer)
queue.enqueue(5)
print(queue.list, queue.endPointer)
queue.enqueue(6)
print(queue.list, queue.endPointer)
queue.enqueue(7)
print(queue.list, queue.endPointer)
queue.dequeue()
print(queue.list)